[pytest]
# 添加源代码目录到 Python 路径
pythonpath = .

# 测试发现规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 避免递归到这些目录
norecursedirs = .git .env* venv*

# 单元测试配置
[unit]
testpaths = tests

# 集成测试配置
[integration]
testpaths = integration_tests